name: Deploy to Firebase Hosting on push to feature branch
'on':
  push:
    branches:
      - feature/**
      - version-**
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.8.1'
      - run: flutter pub get
      - run: flutter build web
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_CONSILIUM_4F21C }}'
          channelId: ${GITHUB_REF_NAME}
          projectId: consilium-4f21c
